### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by boszedave** [boszedave/findmeamechanic#1]
- [ ] Input ellenőrzések
- [ ] Lekezelni, ha nincs GPS és/vagy internet hozzáférés
- [ ] Offline státusz kezelése 
- [x] CardView az előző, lezárt munkákhoz
- [x] CardView-ban lévő elemekre koppintva -> új fragment-be megnyílva több infó
- [ ] Szerelő értékelése
- [ ] Képekhez: Glide
